### ISSUE TITLE
Implement a Killer Feature

### ISSUE THREAD

**Issue by heisig** [preip/WGTools#3]
Nutzer haben die Möglichkeit ein Pool als vollständig zu markieren. Nachdem alle Nutzer des Pools diese Markierung vorgenommen haben, wir der Pool automatisch geschlossen/gesattelt

**Comment by kalinni** [comment]
Und dann kann man auf seinem gesattelten Pool glücklich und zufrieden in den Sonnenuntergang reiten! :D

**Comment by preip** [comment]
done
