### ISSUE TITLE
Time comaprison in pool_isEntryValid wrong

### ISSUE THREAD

**Issue by preip** [preip/WGTools#7]
Apparently, comparing dates in js with < or > operator compares only the day, but not the month, so when a cash pool ranges from the end of one month to the beginning of the next one, no new entries are possible

**Comment by JustusAdam** [comment]
So according to [stackoverflow](https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript) the javascript `Date` is comparable as one would expect. Could it be then that somewhere we actually get a string instead of a date? That would possibly explain the behaviour.

**Comment by preip** [comment]
Might actually be the case, because it comes directly from the HTML form. So we should either convert it to date or compare year, month, and day by hand, whatever is easier (A quick Google search suggests that date in js has all kinds of quirks, so maybe comparing by hand is less painful because its pretty straight forward)

**Comment by JustusAdam** [comment]
Well if the date string has the right format, it should be as easy as `new Date(date_string)`. And even though js is terrible, rolling-your-own is usually worse.
But if you like maybe we can just find a library on npm that does it right?

**Comment by kiliankoe** [comment]
If you want to handle all kinds of date values, I can't recommend [moment](http://momentjs.com) enough. And it can also handle stuff like localizing date values to klingon text 🙆

**Comment by preip** [comment]
fixed with latest update

**Comment by JustusAdam** [comment]
@kiliankoe As far as I understand it, the now deployed "Solution" calls `new Date` on both inputs before comparing it. This "fixes" the problem.

You see, only the highest level of engineering is used in this project.

I would love to redo this entire thing, but I have neither the time, nor the patience to deal with the complaints afterwards because its now Haskell 😐

**Comment by preip** [comment]
If you don't plan to actually contribute anything useful, you can also refrain from commenting at all.

**Comment by kiliankoe** [comment]
Oh you guys... 😄

**Comment by JustusAdam** [comment]
I dare say the first sentence was a useful explanation for kilian :)
